project_name: xelon-cloud-controller-manager

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

before:
  hooks:
    - go mod tidy

builds:
  - binary: '{{ .ProjectName }}'
    flags:
      - -trimpath
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - -s -w
    main: main.go
    mod_timestamp: '{{ .CommitTimestamp }}'

changelog:
  skip: true

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

dist: build

dockers:
  - dockerfile: Dockerfile.release
    goarch: amd64
    goos: linux
    image_templates:
      - "xelonag/xelon-cloud-controller-manager:latest"
      - "xelonag/xelon-cloud-controller-manager:{{ .Tag }}"

env:
  - CGO_ENABLED=0

release:
  draft: false
