linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

output:
  formats:
    - format: tab
  show-stats: true

run:
  timeout: 10m
