FROM alpine:3.18.0

RUN apk add --no-cache ca-certificates \
    # upgrade openssl package to fix vulnerabilities
    && apk add openssl \
    && rm -rf /var/cache/apk/*

ADD xelon-cloud-controller-manager /bin/

CMD ["/bin/xelon-cloud-controller-manager"]
