apiVersion: apps/v1
kind: Deployment
metadata:
  name: xelon-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: xelon-cloud-controller-manager
  template:
    metadata:
      labels:
        app: xelon-cloud-controller-manager
    spec:
      dnsPolicy: Default
      hostNetwork: true
      priorityClassName: ""
      serviceAccountName: xelon-cloud-controller-manager
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
        - key: "node.kubernetes.io/not-ready"
          operator: Exists
          effect: NoSchedule
        - key: "node.kubernetes.io/unreachable"
          operator: Exists
          effect: NoSchedule
      containers:
        - name: xelon-cloud-controller-manager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--leader-elect=false"
            - "--v=2"
          env:
            - name: XELON_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: xelon-api-credentials
                  key: baseUrl
            - name: XELON_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: xelon-api-credentials
                  key: clientId
            - name: XELON_CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: xelon-api-credentials
                  key: cloudId
            - name: XELON_KUBERNETES_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: xelon-api-credentials
                  key: kubernetesClusterId
            - name: XELON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: xelon-api-credentials
                  key: token
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
