version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    working_directory: ~/go/src/xelon-cloud-controller-manager

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build Linux binary"
          command: |
            GOOS=linux go build -o build/xelon-cloud-controller-manager main.go

      - run:
          name: "Build Xelon CCM Docker image"
          command: |
            docker build -t xelonag/xelon-cloud-controller-manager:latest .
