name: Tests

on:
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  push:
    branches: [ master ]
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

permissions:
  contents: read

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Install tools
        run: make tools

      - name: Lint source code
        run: make lint

      - name: Run unit tests
        run: make test
